dataset_dir: data/breps
results_dir: results/association/text-based
extracted_prices_path: data/breps/test/extracted_prices.json
heuristic: gemini
heuristic_kwargs:
  model: gemini-2.5-pro
  price_product_metadata_path: data/metadata/price-product-gemini-pro.json
