accelerator: gpu
batch_size: 16
dataset_dir: data/price-attribution-scenes
gamma: 2.0
logging:
  ckpt_dir: ckpt
  entity: prj-research
  log_dir: logs
  project_name: price-attribution
  use_wandb: true
lr: 3e-4
max_logit_magnitude: 10
model:
  aggregation: none
  featurization:
    use_delta: false
    use_depth: false
    use_price_centroid: true
    use_price_size: true
    use_prod_centroid: true
    use_prod_size: true
  prediction_strategy: marginal
  settings:
    dropout: 0.3
    layer_widths:
    - 256
    - 128
    - 64
num_epochs: 30
num_workers: 0
precision: bf16-mixed
random_seed: 4
run_name: mpn-agg-nodepth-4
warmup_pct: 0.1
weight_decay: 1e-5
