dataset_dir: /home/lgreen/projects/price-net/data/price-attribution-scenes
results_dir: /home/lgreen/projects/price-net/results/gemini-pro-0
cached_attributions_path: /home/lgreen/projects/price-net/vlm-outputs/gemini-pro/0.json