dataset_dir: data/price-attribution-scenes
results_dir: results/gemini-pro
extracted_prices_path: data/price-attribution-scenes/test/extracted_prices.json
heuristic: gemini
heuristic_kwargs:
  model: gemini-2.5-pro
  price_product_metadata_path: data/metadata/price-product-gemini-pro.json
