dataset_dir: data/breps
results_dir: results/attribution/price-lens-oracle-detection-extraction-0
cached_detections_path: data/breps/test/oracle_detections.json
associator_eval_config_path: configs/association/eval/pricenet/0.yaml
split: test
