run_name: test-run
dataset_dir: data/price-graphs-init
model:
  prediction_strategy: marginal
  input_reduction: none
  featurization_method: centroid
  use_depth: true
  settings:
    layer_widths: [128, 64]
    dropout: 0.0
logging:
  use_wandb: false
  project_name: price-attribution
  log_dir: logs
  ckpt_dir: ckpt
num_epochs: 1
batch_size: 1
num_workers: 0
gamma: 0.0
accelerator: cpu
lr: 3e-4
weight_decay: 1e-5
