run_name: jpn-agg-nodiff-nodepth-nosize-0
dataset_dir: data/price-attribution-scenes
model:
  prediction_strategy: joint
  aggregation: closest_per_group
  featurization:
    use_delta: false
    use_prod_centroid: true
    use_price_centroid: true
    use_depth: false
    use_prod_size: false
    use_price_size: false
  settings:
    num_encoder_layers: 3
    d_model: 256
    d_feedforward: 512
    num_heads: 8
    mlp_layer_widths: [256, 128, 64]
    dropout: 0.3
logging:
  use_wandb: true
  project_name: price-attribution
  log_dir: logs
  ckpt_dir: ckpt
num_epochs: 30
batch_size: 16
num_workers: 0
gamma: 2.0
accelerator: gpu
lr: 3e-4
weight_decay: 1e-5
warmup_pct: 0.1
random_seed: 0
precision: bf16-mixed
max_logit_magnitude: 10
