dataset_dir: /home/lgreen/projects/price-net/data/price-attribution-scenes
results_dir: /home/lgreen/projects/price-net/results/gpt-4o-3
cached_attributions_path: /home/lgreen/projects/price-net/vlm-outputs/gpt-4o/3.json
